# Name and short bio (displayed in the header)
name: Davin Hill
title: Davin Hill
author:
  name: Davin Hill
  twitter: davinhill_
description: Sr Research Scientist @ Optum AI

avatar: /profile2_sdr.jpeg
resume: https://drive.google.com/file/d/1TO6IbxqMPfBKObt6mwDZ-lHzF3WJsvlA/view?usp=share_link

# Header icon links
footer-links:
  email: davin_hill@optum.com
  github: davinhill
  linkedin: davinhill
  twitter: davinhill_
  googlescholar: lFRNvCMAAAAJ&hl=en

# Must match CNAME; used for canonical URLs and the sitemap
url: https://www.davinhill.me
baseurl: ""

permalink: /:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# jekyll-seo-tag
defaults:
  - scope:
      path: ""
    values:
      image: /profile2_sdr.jpeg

twitter:
  username: davinhill_
  card: summary

social:
  name: Davin Hill
  links:
    - https://x.com/davinhill_
    - https://www.linkedin.com/in/davinhill/
    - https://github.com/davinhill
    - https://scholar.google.com/citations?user=lFRNvCMAAAAJ
